{ ... }:

{
  # Custom hardware configuration for ae server
  #
  # Note: Basic hardware config (CPU, boot modules, filesystems, swap, networking)
  # is already in /etc/nixos/hardware-configuration.nix (auto-generated by nixos-generate-config)
  #
  # Only add custom hardware settings here (GPU, special peripherals, power management, etc.)
  # For this simple server, no custom hardware config is needed.
}
