{ ... }:

{
  # Custom hardware configuration for nuremberg VPS
  #
  # Note: Basic hardware config (CPU, boot modules, filesystems, swap, networking)
  # is already in /etc/nixos/hardware-configuration.nix (auto-generated by nixos-generate-config)
  #
  # Only add custom hardware settings here (bootloader, special peripherals, power management, etc.)

  #──[Bootloader]────────────────────────────────────────────────────────────

  # VPS bootloader configuration
  # Most VPS providers manage the bootloader - you may not need this section
  # If needed, uncomment and adjust the device path:

  # boot.loader.grub = {
  #   enable = true;
  #   efiSupport = false;
  #   device = "/dev/sda";  # Adjust to your VPS disk device
  #   useOSProber = true;
  # };

  # Clean boot and swap
  boot.tmp.cleanOnBoot = true;
  zramSwap.enable = true;
}
