#──[Display Configuration]─────────────────────────────────────────────────
# See https://wiki.hyprland.org/Configuring/Monitors/

# Main configuration
monitor=eDP-1,1920x1080@60,0x0,1.0
monitor=DP-1,1920x1080@60,1920x0,1.0

# Mirror HDMI to laptop when connected
monitor=HDMI-A-1,preferred,auto,1,mirror,eDP-1
