-- Generated by hyprmon from monitors.json - do not edit.

hl.monitor({ output = "eDP-1", mode = "preferred", position = "0x0", scale = 1, disabled = false, mirror = "" })
hl.monitor({ output = "DP-1", mode = "preferred", position = "auto-left", scale = 1.2, disabled = false, mirror = "" })
