{ ... }:

{
  # Custom hardware configuration for nuremberg VPS
  #
  # Note: Basic hardware config (CPU, boot modules, filesystems, swap, networking)
  # is already in /etc/nixos/hardware-configuration.nix (auto-generated by nixos-generate-config)
  #
  # Only add custom hardware settings here (special peripherals, power management, etc.)
  # The boot loader lives in /etc/nixos/boot.nix, managed per computer by luxos.

  # Clean boot and swap
  boot.tmp.cleanOnBoot = true;
  zramSwap.enable = true;
}
