[settings]
devices = ["Tablet Monitor Pad"]

[shortcuts]
"btn_0" = ">ctrl+z"
"btn_0.hold" = ">ctrl+shift+z"

"btn_1" = "ydotool key 17:1 17:0"
"btn_1.hold" = "ydotool key 25:1 25:0"
#"btn_1.onrelease" = "notify-send huion btn_1"

"btn_2" = "ydotool key 44:1 44:0"

"btn_3" = "notify-send huion btn_3"

"btn_4" = "notify-send huion btn_4"

