[settings]
default_interval = 150

[shortcuts]

	"f1.hold" = "notify-send 'f1 HOLD'"
	"f1.pressrelease" = ["notify-send 'f1 PRESS'", "notify-send 'f1 RELEASE'"]
	"f1.taphold" = "notify-send 'f1 TAPHOLD'"
	"f1.doubletap" = "notify-send 'f1 DOUBLETAP'"

	#"super.doubletap" = "notify-send 'ctrl HOLD'"
    
[command_variables]
