# Auto-generated from machine.toml - DO NOT EDIT
# Generated by self-heal from machine.toml's users array. Edit machine.toml and run: sudo nixos-rebuild switch

{ ... }:

{
  imports = [
    ./user.nix
  ];
}
