-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "eDP-1", mode = "1920x1080@144.00", position = "-640x-960", scale = 1.00 })
hl.monitor({ output = "DP-1", mode = "1920x1080@60.00", position = "1280x32", scale = 1.00 })
